const facts = [
    { range: [0, 2360], fact: "Approximately the amount emitted by an average car driving 10,000 km.", color: "green.500" }, // green
    { range: [2361, 4720], fact: "The emissions generated by the production and transportation of about 100 pairs of jeans.", color: "green.400" },
    { range: [4721, 7080], fact: "Equivalent to the emissions generated by the full lifecycle (from production to recycling) of three smartphones.", color: "green.300" },
    { range: [7081, 9440], fact: "The amount of emissions generated by using gas heating in a typical European home for a year.", color: "yellow.100" },
    { range: [9441, 11800], fact: "Equivalent to the energy needed to power an average refrigerator for 10 years.", color: "yellow.200" }, // yellow
    { range: [11801, 14160], fact: "The emissions generated by the production and use of an average electric car for about 6 years.", color: "yellow.300" },
    { range: [14161, 16520], fact: "Equivalent to the emissions generated by one large truck transporting goods over a distance of 50,000 km.", color: "yellow.400" },
    { range: [16521, 18880], fact: "The emissions generated by a single cargo ship transporting containers from China to Europe.", color: "red.300" },
    { range: [18881, 21240], fact: "Equivalent to the emissions generated by the production and use of 500 kg of beef (around 30 large steaks).", color: "red.400" }, // red
    { range: [21241, 23600], fact: "The emissions equivalent to the production and transportation of materials to build a small single-family house.", color: "red.500" } // red
];

function get_fact(score) {
    for (let i = 0; i < facts.length; i++) {
        if (score >= facts[i].range[0] && score <= facts[i].range[1]) {
            return [facts[i].fact, facts[i].color, true];
        }
    }

    return ["It looks no more facts for you, sorry...", "#000000", false];
}

export default get_fact;